#Server configuration
server.servlet.context-path=/cham
server.port=8087
### DATABASE ###
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/excham1?useUnicode=true&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
### JPA / HIBERNATE ###
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

#logging configuration
logging.level.com.zaxxer.hikari=warn
logging.level.org.springframework=warn

logging.level.root= info
logging.level.com.example.menu.services.ClientService = debug
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %-5level - %logger{60} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm} - %-5level- %logger{36} - %msg %n
